### ISSUE TITLE
Investigate: Communicating into to the freedeck over serial using AHK on windows

### ISSUE THREAD

**Issue by legomannetje** [FreeYourStream/freedeck-tools#3]
On linux everything is a file, so that would be easy

Have some info going back to the Freedeck so you can change the interface depending on variables on the host machine

**Comment by legomannetje** [comment]
https://www.autohotkey.com/boards/viewtopic.php?t=14978

**Comment by koriwi** [comment]
you could use this linux script as a starting point for windows
https://github.com/FreeYourStream/freedeck-tools/blob/master/linux/page%20switch/auto_page_switch.sh

**Comment by legomannetje** [comment]
Implemented it in python and in powershell (windows native) since batch isn't exactly working. PR #6

**Comment by legomannetje** [comment]
The functions can be implemented with the code from PR #6, so we can close this issue
